name: MealSwipe Backend CI Testing

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setting up NodeJS version.
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present
            
      - name: Run tests on built swipe.
        working-directory: ./backend
        run: npm test
